// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVi1VwFdwKBK-osmIzmlsodDLpUPA6MFo',
    appId: '1:234422163440:android:c1771d61f18f71074c2f35',
    messagingSenderId: '234422163440',
    projectId: 'zeta-ess',
    databaseURL: 'https://zeta-ess.firebaseio.com',
    storageBucket: 'zeta-ess.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYv0TXelGnefwGFpkJuSapUV44Bvq_nG8',
    appId: '1:234422163440:ios:f72ba0cde8b5b8034c2f35',
    messagingSenderId: '234422163440',
    projectId: 'zeta-ess',
    databaseURL: 'https://zeta-ess.firebaseio.com',
    storageBucket: 'zeta-ess.firebasestorage.app',
    androidClientId: '234422163440-1h7t84vcvbm5f8t3i5coikde21etffta.apps.googleusercontent.com',
    iosClientId: '234422163440-5n1qdm63h0m79h4pd1rqdul28td1fq8h.apps.googleusercontent.com',
    iosBundleId: 'com.zeta.zetaEss',
  );

}